export default {
  index: {},
  'quick-start': { theme: { collapsed: true } },
  view: { theme: { collapsed: true } },
  component: { theme: { collapsed: true } },
  part: { theme: { collapsed: true } },
  feature: { theme: { collapsed: true } },
  examples: { theme: { collapsed: true } },
  shortcuts: {},
  faq: {},
  updates: { theme: { collapsed: true } },
  legal: { theme: { collapsed: true } },
  about: { },
  'beta-end': { title: <span style={{ color: '#F49F00' }}>Beta Ending Soon</span> },
}
