export default {
  index: {},
  'quick-start': { theme: { collapsed: true } },
  view: { theme: { collapsed: true } },
  component: { theme: { collapsed: true } },
  part: { theme: { collapsed: true } },
  feature: { theme: { collapsed: true } },
  examples: { theme: { collapsed: true } },
  faq: {},
  updates: { theme: { collapsed: true } },
  legal: { theme: { collapsed: true } },
  'brand-assets': { },
  about: {},
  'pro-plan': { title: 'Plans', theme: { collapsed: true } },
  'partnership-program': { display: 'hidden' },
}