export default {
  index: {},
  'quick-start': { theme: { collapsed: true } },
  guides: { title: 'Guides', theme: { collapsed: true } },
  view: { theme: { collapsed: true } },
  component: { theme: { collapsed: true } },
  part: { theme: { collapsed: true } },
  feature: { title: 'Features', theme: { collapsed: true } },
  examples: { theme: { collapsed: true } },
  faq: {},
  updates: { theme: { collapsed: true } },
  legal: { theme: { collapsed: true } },
  'brand-assets': { },
  about: {},
  'plan': { title: 'Plans', theme: { collapsed: true } },
  'partnership-program': { display: 'hidden' },
  'student-team-program': { display: 'hidden' },
}