export default {
  "component-connector": "",
  "component-terminal": "",
  "component-wire": "",
  "component-layout-point": "",
  "component-splice": "",
  "component-cable": "",
  "component-twisted-wires": "",
  "component-diode": "",
  "component-resistor": "",
  "component-bundle": "",
  "component-branch-point": "",
  "component-group": "",
  "component-net-label": "",
};
